### ISSUE TITLE
Crash on this.log

### ISSUE THREAD

**Issue by wiggertdehaan** [wiggertdehaan/open_epaper_link_homey#35]
TypeError: this.log is not a function
    at CardManager.SaveJSON (/app/cardManager.js:605:14)
    at CardManager.cardShowLocalJSON (/app/cardManager.js:594:14)
    at /app/app.js:89:24
    at FlowCardAction._run (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCard.js:92:30)
    at ManagerFlow._onFlowCardRun (/node_modules/@athombv/homey-apps-sdk-v3/manager/flow.js:179:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by wiggertdehaan** [comment]
Fixed on `main`.

`CardManager` is a plain class constructed with the app as its `homey` argument, so it has no `log()` method of its own - `this.log(...)` was always going to throw, it just needed the local-JSON card to be run to get there.

Every call in `cardManager.js`, `tagManager.js` and `apManager.js` now goes through `this.homey.log(...)`. There are zero remaining `this.log(` calls in those three files.
